### ISSUE TITLE
Sivun pyyhkäisy sivuttain on liian herkkä

### ISSUE THREAD

**Issue by vurpo** [DigitKoodit/UrhoMatti-3.0#16]
Laulua skrollatessa on erittäin helppo vahingossa siirtyä edelliseen tai seuraavan lauluun, kun sovellus tunnistaa niin herkästi sivutain pyyhkäisyn. Miten usein esim. sitseillä tarvitsee siirtyä numerojärjestyksessä seuraavaan tai edelliseen lauluun?

**Comment by PetroSilenius** [comment]
Addressed and fixed in #17!
