### ISSUE TITLE
Missing lyrics in song 202

### ISSUE THREAD

**Issue by ruohola** [DigitKoodit/UrhoMatti-3.0#18]
Love the app! Found a pretty massive problem with the song lyrics :( My favorite song *202. Tonttujen jouluyö* is missing a part of the lyrics. I believe the verse that was missing was supposed to start with the words "Jouluruokaa tarjoo kunnon väki".

Please fix this asap, thanks!

**Comment by PetroSilenius** [comment]
Thanks for the feedback and active usage @ruohola! It seems like you're the first user who ran in to this missing verse, but cool that you did. We've added to this to our product backlog and will prioritise is during our next refinement session. I have a feel we might get this fixed sooner than you think. Will get back to you soon!

**Comment by PetroSilenius** [comment]
And once again you can see the fast development speed here at Digit Ventures. Issue closed and fixed in the web application. Native Android app will be updated once we make a new release✌🏻
